#!/bin/bash

########## LOGBUCH ###
LOGBUCH=~/.local/log.cs
# letzten command ins logbuch eintragen 	$ log 
# vorletzten command ins logbuch   			$ nlog 1
function log() {
	echo $(whoami)@$(/usr/bin/date +%F/%R)$(history | tail -n 2 | head -n 1 | sed 's/ .[0-9]\+ /$/') >> $LOGBUCH
}
function nlog() {
	echo $(whoami) $(/usr/bin/date +%F/%R) $(history | tail -n "$(($1+2))" | head -n 1) >> $LOGBUCH
}
alias vlog="vim $LOGBUCH"
alias clog="cat $LOGBUCH"


########### check if a package is INSTALLED
Check () {
	dpkg -s $1 | head -n 2
}


######### CALCULATE
function c { python -c "print("$1")" ;}
### CALCULATE Only with bash
function ca { echo "$(($1))" ; }

############ TIMER
alias tell=" cvlc ~/Music/* vlc://quit" 
#function alarm { date && sleep "$1" && [ -v $2 ] && tell &> /dev/null && return ; vlc ; }
function alarm { date && sleep "$1" && if [ -z $2 ] ; then  echo "$2" ; vlc  ; else  tell ; fi ;   } 
function since() {
	date1=$(ps -eo pid,tty,start,cmd,user | grep -i $1 | grep $(whoami) | grep -v grep | awk '{print $3}')
	date2=$(/usr/bin/date +'%H:%M:%S') 
	datediff -i '%H:%M:%S' -f '%0H:%0M:%0S' $date1 $date2
}

########### BACKLIGHT
#function light { echo $1 > /sys/class/backlight/intel_backlight/brightness ; }
#function minlight { echo 1 > /sys/class/backlight/intel_backlight/brightness ; }
function light { xbacklight = $1 ; }
function minlight { xbacklight = 0.1; }
function mkcd { mkdir $1; cd $1; }

### ICD
if [ -f /home/pur/.icd/icd ] ; then source /home/pur/.icd/icd ; fi

# function rm { mv "$1 ~/.trash/" ; }

TRKFILE=$HOME/.trk
function trk {
	if [ $# -eq 0 ] ; then 
		tail $TRKFILE
	else 
		echo `command date +%Y.%m.%d-%H:%M` "> $@" >> $TRKFILE
	fi
}

### GTAR 
function gtar {
    USAGE='''
\tUSAGE: $0 [-c|-x] [dir|dir.tar.gz.gpg]\n
        \t\t-c create\n
        \t\t-x extract\n
    '''
    EXTENSION='tar.gz.gpg'
    if [ $# != 2 ] ; then 
        echo -ne $USAGE
        return 1;
    elif [ $1 == "-c" ] ; then
        echo '$1 is -c'
        echo '$2 is '"${2%/}"
        tar czf - ${2%/} | gpg -c > ${2%/}.$EXTENSION
    elif [ $1 == "-x" ] ; then 
        echo '$1 is -x'
        echo '$2 is '"${2%/}"
        gpg -d $2 | tar xzf - 
    fi
}

### SUMOUNT 
function au { 
    if [[ $# -eq 0 ]] ; then 
        device=$(df -ha| grep systemd| grep run | tr -s ' ' | cut -d' ' -f6 | dmenu -l 2 -b -i)
        sudo systemd-mount -u $device
    elif [[ $# -eq 1 ]] ; then 
        sudo systemd-mount -u $1
    else 
        echo "ERROR: too many arguments"
    fi
}
