#KSHRC
#
. /etc/ksh.kshrc
#
export PS1='[\u@\h(\s) \w]\$ '
#
export XDG_CONFIG_HOME=$HOME/.config.git
[ -f $XDG_CONFIG_HOME/shell/shellrc ] && . $XDG_CONFIG_HOME/shell/shellrc
#
[ -f $XDG_CONFIG_HOME/.ksh_aliases ] && . $XDG_CONFIG_HOME/.ksh_aliases
[ -f $HOME/.ksh_aliases ] && . $HOME/.ksh_aliases
[ -f $HOME/.ksh_local ] && . $HOME/.ksh_local
