[ids]
*

[main]
# Swap meta and alt key https://github.com/rvaiya/keyd/issues/955
leftalt = layer(meta)
rightalt = layer(meta)
leftmeta = layer(alt)
rightmeta = layer(altgr)

# remap key next to left shift to ` and ~
102nd = `

# add delete key
[shift] 
backspace = delete

[control]
backspace = delete
