#
# ~/.bashrc
#

export EDITOR=vim
export BROWSER=brave
LANG=en_US.UTF-8
HISTSIZE=-1
PS1='[\u@\h \W]\$ '

# IF NOT RUNNING INTERACTIVELY, DON'T DO ANYTHING
[[ $- != *i* ]] && return

# VI CONTROL IN BASH
set -o vi

# SOURCE ALIASES AND FUNCTIONS
export XDG_CONFIG_HOME=~/.config.git
if [ -f ~/.bash_aliases ] ; then source ~/.bash_aliases ; fi
if [ -f $XDG_CONFIG_HOME/bash/bash_aliases ] ; then source $XDG_CONFIG_HOME/bash/bash_aliases ; fi

if [ -f ~/.bash_functions ] ; then source ~/.bash_functions ; fi
if [ -f $XDG_CONFIG_HOME/bash/bash_functions ] ; then source $XDG_CONFIG_HOME/bash/bash_functions ; fi

if [ -f ~/.bash_local ] ; then source ~/.bash_local; fi
if [ -f $XDG_CONFIG_HOME/bash/bash_local ] ; then source $XDG_CONFIG_HOME/bash/bash_local; fi

PATH=$PATH:~/.local/bin
PATH=$PATH:$XDG_CONFIG_HOME/bin

if [ -f /home/pur/.icd/icd ] ; then source /home/pur/.icd/icd ; fi
